### ISSUE TITLE
After Every command...

### ISSUE THREAD

**Issue by austin-thesing** [zeg-io/git-aware-terminal#2]
Hey Guys after every command I see this in my terminal and it makes reading readouts and commands such a pain.. I will have to disable this until it is working properly..

<img width="487" alt="screen shot 2016-02-27 at 7 31 26 pm" src="https://cloud.githubusercontent.com/assets/13810854/13377272/ba45777c-dd88-11e5-8466-ed451effc74a.png">

**Comment by zeg-io** [comment]
This was resolved by the contributed code from @mwieder and is included in v1.0.2-Beta
